import React, { useState, useMemo } from 'react';
import {
  X,
  Copy,
  Check,
  Download,
  Share2,
  FileCode,
  Sparkles,
  Layers,
  Bot,
  ExternalLink
} from 'lucide-react';
import { CodeGraph, NodeType } from '../../types';

interface ExportDiagramModalProps {
  isOpen: boolean;
  onClose: () => void;
  graph: CodeGraph | null;
}

export const ExportDiagramModal: React.FC<ExportDiagramModalProps> = ({
  isOpen,
  onClose,
  graph
}) => {
  const [activeTab, setActiveTab] = useState<'mermaid' | 'c4' | 'cursorrules' | 'rawjson'>('mermaid');
  const [copied, setCopied] = useState(false);

  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    if (isOpen) {
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  // Generate Mermaid Flowchart Syntax
  const mermaidSyntax = useMemo(() => {
    if (!graph || !graph.nodes || graph.nodes.length === 0) {
      return '%% No graph data available to export';
    }

    const sanitizeId = (id: string) =>
      id.replace(/[^a-zA-Z0-9_]/g, '_');

    const lines: string[] = [];
    lines.push('```mermaid');
    lines.push('flowchart TD');
    lines.push(`    %% CodeGraph AI Export: ${graph.projectName || 'Architecture'}`);
    lines.push('    %% Generated by CodeGraph AI (https://github.com/manishmks24/codeGraph)\n');

    // Group by NodeType
    const groups: Partial<Record<NodeType, string>> = {
      ENDPOINT: 'API Endpoints & Triggers',
      CONTROLLER: 'Controllers & Route Handlers',
      SERVICE: 'Core Domain Services',
      REPOSITORY: 'Repositories & Data Access',
      ENTITY: 'Domain Entities & Models',
      EVENT_LISTENER: 'Async Event & Message Handlers',
      COMPONENT: 'UI & Application Components'
    };

    Object.entries(groups).forEach(([type, label]) => {
      const typeNodes = graph.nodes.filter(n => n.type === type);
      if (typeNodes.length > 0) {
        lines.push(`    subgraph sg_${type} ["${label}"]`);
        typeNodes.forEach(node => {
          const safeId = sanitizeId(node.id);
          const cleanName = node.name.replace(/"/g, "'");
          lines.push(`        ${safeId}["${cleanName}"]`);
        });
        lines.push('    end\n');
      }
    });

    // Edges
    if (graph.edges && graph.edges.length > 0) {
      lines.push('    %% Inter-Component Relationships');
      graph.edges.forEach(edge => {
        const sourceSafe = sanitizeId(edge.sourceId);
        const targetSafe = sanitizeId(edge.targetId);
        const label = edge.label ? `|"${edge.label.replace(/"/g, "'")}"|` : '';
        lines.push(`    ${sourceSafe} -->${label} ${targetSafe}`);
      });
    }

    // Styling
    lines.push('\n    %% Layer Styling');
    lines.push('    classDef endpoint fill:#0284c7,stroke:#0369a1,color:#ffffff;');
    lines.push('    classDef controller fill:#3b82f6,stroke:#1d4ed8,color:#ffffff;');
    lines.push('    classDef service fill:#9333ea,stroke:#7e22ce,color:#ffffff;');
    lines.push('    classDef repository fill:#d97706,stroke:#b45309,color:#ffffff;');
    lines.push('    classDef entity fill:#059669,stroke:#047857,color:#ffffff;');
    lines.push('    classDef listener fill:#dc2626,stroke:#b91c1c,color:#ffffff;');

    graph.nodes.forEach(node => {
      const safeId = sanitizeId(node.id);
      const styleMap: Partial<Record<NodeType, string>> = {
        ENDPOINT: 'endpoint',
        CONTROLLER: 'controller',
        SERVICE: 'service',
        REPOSITORY: 'repository',
        ENTITY: 'entity',
        EVENT_LISTENER: 'listener'
      };
      const cls = styleMap[node.type];
      if (cls) {
        lines.push(`    class ${safeId} ${cls};`);
      }
    });

    lines.push('```');
    return lines.join('\n');
  }, [graph]);

  // Generate C4 Model Markdown
  const c4Markdown = useMemo(() => {
    if (!graph) return '';
    const projectName = graph.projectName || 'Software System';
    return `# C4 Architecture Model — ${projectName}
*Generated by **CodeGraph AI** on ${new Date().toISOString().split('T')[0]}*

---

## 1. System Context & Overview
The **${projectName}** architecture contains **${graph.nodes?.length || 0} core components** and **${graph.edges?.length || 0} dependency edges**.

### Component Breakdown by Layer:
| Layer / Type | Component Count | Description |
| :--- | :--- | :--- |
| **API Endpoints** | ${graph.nodes?.filter(n => n.type === 'ENDPOINT').length || 0} | Public REST / GraphQL / Route triggers |
| **Controllers** | ${graph.nodes?.filter(n => n.type === 'CONTROLLER').length || 0} | Request routing and input validation |
| **Services** | ${graph.nodes?.filter(n => n.type === 'SERVICE').length || 0} | Domain logic and business rules |
| **Data Repositories** | ${graph.nodes?.filter(n => n.type === 'REPOSITORY').length || 0} | Database persistence and ORM queries |
| **Entities / Models** | ${graph.nodes?.filter(n => n.type === 'ENTITY').length || 0} | Data schemas and domain models |
| **Event Listeners** | ${graph.nodes?.filter(n => n.type === 'EVENT_LISTENER').length || 0} | Async Kafka / RabbitMQ message consumers |

---

## 2. Key Components Catalog
${graph.nodes?.map(n => `- **${n.name}** (\`${n.type}\` in \`${n.packageName || 'root'}\`): ${n.linesOfCode ? `${n.linesOfCode} LOC` : 'N/A'}`).join('\n') || ''}

---

## 3. Dependency Call Flows
\`\`\`mermaid
flowchart LR
${graph.edges?.slice(0, 30).map(e => `    ${e.sourceId.replace(/[^a-zA-Z0-9_]/g, '_')} --> ${e.targetId.replace(/[^a-zA-Z0-9_]/g, '_')}`).join('\n') || ''}
\`\`\`
`;
  }, [graph]);

  // Generate .cursorrules / GEMINI.md AI Guardrails
  const cursorRules = useMemo(() => {
    if (!graph) return '';
    const projectName = graph.projectName || 'Project';
    const controllers = graph.nodes?.filter(n => n.type === 'CONTROLLER').map(n => n.name).join(', ') || 'N/A';
    const services = graph.nodes?.filter(n => n.type === 'SERVICE').map(n => n.name).join(', ') || 'N/A';
    const repos = graph.nodes?.filter(n => n.type === 'REPOSITORY').map(n => n.name).join(', ') || 'N/A';

    return `# CodeGraph AI Architecture Guardrails for ${projectName}
# Place this file as .cursorrules, GEMINI.md, or in your AI Agent context.

You are an expert software architect assisting with the "${projectName}" codebase.
Strictly adhere to the following architectural rules and topological boundaries:

## 1. Architectural Layers & Boundaries
- **Controllers / Route Handlers**: [${controllers}]
  - Responsible ONLY for HTTP routing, request parsing, and status codes.
  - MUST delegate all business logic to Service layer components.
  - NEVER directly call or inject Repositories or database clients.

- **Domain Services**: [${services}]
  - Encapsulate business workflows and domain rules.
  - Call Repositories for persistence.
  - Manage database transaction boundaries.
  - Do NOT introduce circular dependencies with other services.

- **Repositories / Data Access**: [${repos}]
  - Strictly handle database queries and entity persistence.

## 2. Forbidden Anti-Patterns
1. ❌ Circular Dependency between Services.
2. ❌ Direct Controller-to-Repository bypassing the Service layer.
3. ❌ Entities importing or calling Controller/Service logic.
4. ❌ Modifying critical shared services without running CodeGraph Blast Radius analysis.

## 3. Before Submitting Changes
- Ensure no architectural violations are introduced.
- Verify downstream blast radius on all impacted controllers and services.
`;
  }, [graph]);

  const currentContent = useMemo(() => {
    switch (activeTab) {
      case 'mermaid':
        return mermaidSyntax;
      case 'c4':
        return c4Markdown;
      case 'cursorrules':
        return cursorRules;
      case 'rawjson':
        return JSON.stringify(graph, null, 2);
    }
  }, [activeTab, mermaidSyntax, c4Markdown, cursorRules, graph]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(currentContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const handleDownload = () => {
    const extMap = {
      mermaid: 'mmd',
      c4: 'md',
      cursorrules: 'md',
      rawjson: 'json'
    };
    const filename = `${graph?.projectName?.toLowerCase().replace(/\s+/g, '-') || 'codegraph'}-${activeTab}.${extMap[activeTab]}`;
    const blob = new Blob([currentContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (!isOpen) return null;

  return (
    <div
      onClick={onClose}
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/70 backdrop-blur-md animate-in fade-in text-slate-900 dark:text-slate-100"
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl w-full max-w-4xl max-h-[88vh] flex flex-col overflow-hidden text-slate-900 dark:text-slate-100 transition-colors duration-200"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                Export Architecture & AI Guardrails
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                1-click export for GitHub READMEs, Notion, Mermaid, and Cursor/Gemini AI agents
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center gap-2 px-6 pt-3 border-b border-slate-200 dark:border-slate-800 bg-slate-50/30 dark:bg-slate-900/30">
          {[
            { id: 'mermaid', label: 'Mermaid.js Diagram', icon: Layers },
            { id: 'c4', label: 'C4 Architecture Model', icon: FileCode },
            { id: 'cursorrules', label: 'Cursor / Gemini Rules', icon: Bot },
            { id: 'rawjson', label: 'Raw JSON Graph', icon: Sparkles }
          ].map(tab => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`flex items-center gap-2 px-4 py-2.5 text-xs font-semibold rounded-t-xl transition-all border-b-2 ${
                  isActive
                    ? 'border-emerald-600 dark:border-emerald-400 text-emerald-600 dark:text-emerald-400 bg-white dark:bg-slate-900'
                    : 'border-transparent text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
                }`}
              >
                <Icon className="w-4 h-4" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Code Content Viewer */}
        <div className="flex-1 p-6 overflow-hidden flex flex-col">
          <div className="relative flex-1 bg-slate-950 rounded-xl border border-slate-800 overflow-hidden flex flex-col font-mono text-xs">
            <div className="flex items-center justify-between px-4 py-2 bg-slate-900 border-b border-slate-800 text-slate-400">
              <span className="text-[11px]">
                {activeTab === 'mermaid' && 'Paste directly into GitHub Markdown or Mermaid Live Editor'}
                {activeTab === 'c4' && 'Complete architectural documentation with component matrix'}
                {activeTab === 'cursorrules' && 'Saves to .cursorrules or GEMINI.md to constrain AI agents'}
                {activeTab === 'rawjson' && 'Topological Graph AST Export'}
              </span>
              {activeTab === 'mermaid' && (
                <a
                  href="https://mermaid.live"
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-1 text-[11px] text-emerald-400 hover:text-emerald-300 transition-colors"
                >
                  <span>Open Mermaid Live</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              )}
            </div>

            <pre className="flex-1 p-4 overflow-auto text-slate-300 leading-relaxed select-all">
              <code>{currentContent}</code>
            </pre>
          </div>
        </div>

        {/* Action Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50">
          <div className="text-xs text-slate-500 dark:text-slate-400 flex items-center gap-2">
            <span>💡 Use Mermaid diagrams in GitHub READMEs for rich visual architecture</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700 transition-all shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>

            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-4 py-2 text-xs font-semibold rounded-xl transition-all shadow-sm ${
                copied
                  ? 'bg-emerald-600 text-white'
                  : 'bg-emerald-600 hover:bg-emerald-500 text-white dark:text-slate-950 dark:bg-emerald-400 dark:hover:bg-emerald-300'
              }`}
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy to Clipboard'}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
